// generated by stringer -output=string.go -type=ErrorCode,Opcode; DO NOT EDIT

package tftp

import "fmt"

const _ErrorCode_name = "ErrorCodeUndefinedErrorCodeFileNotFoundErrorCodeAccessViolationErrorCodeDiskFullErrorCodeIllegalOperationErrorCodeUnknownTransferIDErrorCodeFileExistsErrorCodeNoSuchUser"

var _ErrorCode_index = [...]uint8{0, 18, 39, 63, 80, 105, 131, 150, 169}

func (i ErrorCode) String() string {
	if i >= ErrorCode(len(_ErrorCode_index)-1) {
		return fmt.Sprintf("ErrorCode(%d)", i)
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}

const _Opcode_name = "OpcodeReadOpcodeWriteopcodeDATAopcodeACKOpcodeError"

var _Opcode_index = [...]uint8{0, 10, 21, 31, 40, 51}

func (i Opcode) String() string {
	i -= 1
	if i >= Opcode(len(_Opcode_index)-1) {
		return fmt.Sprintf("Opcode(%d)", i+1)
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
